// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASu_9MfYFdVJY8Vn02KltxfSf-ai185i4',
    appId: '1:634146131992:web:186a74ceed9a48923eb36d',
    messagingSenderId: '634146131992',
    projectId: 'moodbuddy-f0928',
    authDomain: 'moodbuddy-f0928.firebaseapp.com',
    storageBucket: 'moodbuddy-f0928.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrNYe6D0W6IPrS1q9o9WbGozQt-hYrq50',
    appId: '1:634146131992:android:7c59152e61829b193eb36d',
    messagingSenderId: '634146131992',
    projectId: 'moodbuddy-f0928',
    storageBucket: 'moodbuddy-f0928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTaeyck3_ssXUx37ozLZeEHoZqeFZB6rs',
    appId: '1:634146131992:ios:114d37406c5bf12c3eb36d',
    messagingSenderId: '634146131992',
    projectId: 'moodbuddy-f0928',
    storageBucket: 'moodbuddy-f0928.firebasestorage.app',
    iosBundleId: 'com.example.moodbuddyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTaeyck3_ssXUx37ozLZeEHoZqeFZB6rs',
    appId: '1:634146131992:ios:114d37406c5bf12c3eb36d',
    messagingSenderId: '634146131992',
    projectId: 'moodbuddy-f0928',
    storageBucket: 'moodbuddy-f0928.firebasestorage.app',
    iosBundleId: 'com.example.moodbuddyApp',
  );
}
